settings:
  join-message: false
  quit-message: false
  toggle-fly: true
  health: 20.0
  min-y: 0.0
  speed: 7.0
  allowed-commands:
    - /spawn
    - /menu
    - /license
    - /logout
    - /changepassword
    - /hide
    - /show

# All changes required restart plugin
# If disabled, the following commands are available: "/hide", "/show"
hider:
  enable: false # for 1.13+ (disable if below)
  slot: 4 # 0-8
  shown:
    material: GRAY_DYE
    name: "&aПоказать игроков"
    sound:
      enable: false
      name: ENTITY_PLAYER_LEVELUP
      pitch: 1.0
      volume: 0.5
  hidden:
    material: LIME_DYE
    name: "&7Скрыть игроков"
    sound:
      enable: false
      name: ENTITY_PLAYER_LEVELUP
      pitch: 1.0
      volume: 0.5