name: LightHub
version: '${project.version}'
description: '${description}'
api-version: 1.13

main: ru.kainlight.lighthub.Main
load: POSTWORLD

commands:
  lightgamemode:
    usage: /gm <number> (<username>)
    aliases:
      - gm
  lightfly:
    usage: /fly (<username>)
    aliases:
      - fly
  lighthub: { }
  lightspawn:
    aliases:
      - spawn
  hide:
    description: Hide all players
  show:
    description: Show all players

permissions:
  lighthub.visibility:
    default: true
  lighthub.gamemode:
    default: op
  lighthub.gamemode.other:
    default: op
    children:
      lighthub.gm: true
  lighthub.gamemode.*:
    default: op
    children:
      lighthub.gamemode: true
      lighthub.gamemode.other: true
  lighthub.fly:
    default: op
  lighthub.fly.other:
    default: op
    children:
      lighthub.fly: true
  lighthub.fly.*:
    default: op
    children:
      lighthub.fly: true
      lighthub.fly.other: true
  lighthub.spawn:
    default: true
  lighthub.spawn.create:
    default: op
    children:
      lighthub.spawn: true
  lighthub.inv.drop:
    default: op
  lighthub.inv.pickup:
    default: op
  lighthub.inv.move:
    default: op
  lighthub.inv.*:
    default: op
    children:
      lighthub.inv.drop: true
      lighthub.inv.pickup: true
      lighthub.inv.move: true
  lighthub.pickup:
    default: op
  lighthub.block.break:
    default: op
  lighthub.block.place:
    default: op
  lighthub.block.*:
    default: op
    children:
      lighthub.block.break: true
      lighthub.block.place: true
  lighthub.damage:
    default: op
  lighthub.*:
    default: op
    children:
      lighthub.visibility: true
      lighthub.gamemode: true
      lighthub.gamemode.other: true
      lighthub.fly: true
      lighthub.fly.other: true
      lighthub.spawn: true
      lighthub.inv.*: true
      lighthub.pickup: true
      lighthub.block.*: true
      lighthub.damage: true